name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Compile Test Classes
      run: |
        mkdir -p target/classes
        javac -cp .:wrangler-api/src/main/java -d target/classes ByteSizeTest.java
        javac -cp .:wrangler-api/src/main/java -d target/classes TimeDurationTest.java
    
    - name: Run Tests
      run: |
        java -cp .:wrangler-api/src/main/java:target/classes ByteSizeTest
        java -cp .:wrangler-api/src/main/java:target/classes TimeDurationTest
